// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechTask.Persistence.Context;

namespace TechTask.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190701144246_RemovedDateTimePropsFromTasks")]
    partial class RemovedDateTimePropsFromTasks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TechTask.Persistence.Models.Task.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<int>("TasksId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TasksId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Task.TaskPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("TaskPriorities");
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Task.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("PriorityId");

                    b.Property<int>("Status");

                    b.Property<int?>("TeamId");

                    b.Property<Guid?>("TrackerId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Users.LoggedActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<DateTime>("HoursSpent");

                    b.Property<int>("TasksId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TasksId");

                    b.HasIndex("UserId");

                    b.ToTable("LoggedActivities");
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Users.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("HoursOfWorkOnAllTasks");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 28, DateTimeKind.Local).AddTicks(5864),
                            HoursOfWorkOnAllTasks = 0,
                            Name = "Alpha",
                            UpdatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 31, DateTimeKind.Local).AddTicks(658)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 31, DateTimeKind.Local).AddTicks(2930),
                            HoursOfWorkOnAllTasks = 0,
                            Name = "Beta",
                            UpdatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 31, DateTimeKind.Local).AddTicks(2947)
                        });
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("Role");

                    b.Property<int?>("TeamId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfd23b66-1a4e-41de-4aa7-08d6fae3b08b"),
                            CreatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 36, DateTimeKind.Local).AddTicks(3485),
                            DateOfBirth = new DateTime(1984, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "will.s@tech.com",
                            FirstName = "Will",
                            LastName = "Stevens",
                            Password = "Will123",
                            Role = 0,
                            TeamId = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 36, DateTimeKind.Local).AddTicks(3516)
                        },
                        new
                        {
                            Id = new Guid("76aebd31-0235-4ef3-a123-08d6fbc1bdcd"),
                            CreatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 36, DateTimeKind.Local).AddTicks(5876),
                            DateOfBirth = new DateTime(1993, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.s@tech.com",
                            FirstName = "John",
                            LastName = "Smith",
                            Password = "John123",
                            Role = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 36, DateTimeKind.Local).AddTicks(5890)
                        },
                        new
                        {
                            Id = new Guid("ed09fe47-84c0-47b5-8007-ae2ea4350a8b"),
                            CreatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 36, DateTimeKind.Local).AddTicks(7804),
                            DateOfBirth = new DateTime(1973, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.w@tech.com",
                            FirstName = "Jane",
                            LastName = "Williams",
                            Password = "Jane123",
                            Role = 0,
                            TeamId = 2,
                            UpdatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 36, DateTimeKind.Local).AddTicks(7813)
                        },
                        new
                        {
                            Id = new Guid("f3c88d42-fb42-43c4-a9d4-1a738a2bd20c"),
                            CreatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 36, DateTimeKind.Local).AddTicks(7858),
                            DateOfBirth = new DateTime(1988, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anthony.r@tech.com",
                            FirstName = "Anthony",
                            LastName = "Russell",
                            Password = "Anthony123",
                            Role = 1,
                            UpdatedAt = new DateTime(2019, 7, 1, 17, 42, 46, 36, DateTimeKind.Local).AddTicks(7862)
                        });
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Task.Comment", b =>
                {
                    b.HasOne("TechTask.Persistence.Models.Task.Tasks")
                        .WithMany("Comments")
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TechTask.Persistence.Models.Users.User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Task.Tasks", b =>
                {
                    b.HasOne("TechTask.Persistence.Models.Task.TaskPriority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.HasOne("TechTask.Persistence.Models.Users.Team")
                        .WithMany("Tasks")
                        .HasForeignKey("TeamId");

                    b.HasOne("TechTask.Persistence.Models.Users.User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Users.LoggedActivity", b =>
                {
                    b.HasOne("TechTask.Persistence.Models.Task.Tasks")
                        .WithMany("Log")
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TechTask.Persistence.Models.Users.User")
                        .WithMany("Log")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TechTask.Persistence.Models.Users.User", b =>
                {
                    b.HasOne("TechTask.Persistence.Models.Users.Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
